version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Start up Services
          command: |
            docker-compose up -d database redis zookeeper kafka
            docker-compose ps
      - run:
          name: Build Up Server
          command: |
            docker-compose build server
      - run:
          name: Show All Image
          command: |
            docker images

      - run:
          name: Test and verify code coverage
          command: |
            docker run -it --name testcontainer dockerapp1_server sh -c "cd /server;mvn clean verify"
      - run:
          name: Transfer artifacts to local machine
          command: |
            docker create -ti --name artifacts dockerapp1_server bash
            docker cp artifacts:/server/target  /dockerapp1
            docker rm -f artifacts

      - store_artifacts:
            path: target/surefire-reports





