version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Start up Services
          command: |
            docker-compose up -d database redis zookeeper kafka
            docker-compose ps
      - run:
          name: Build Up Server
          command: |
            docker-compose build server

      - run:
          name: Setup a Testcontainer
          command: |
            docker run -it --name testcontainer dockerapp1_server sh -c "cd /server;mvn clean test"
            docker run -it --name testcontainer2 dockerapp1_server sh -c "cd server"
      - store_artifacts:
            path: target
      - codecov/upload:
           file: './coverage/clover.xml'
           token: 2b40e5a9-4a6c-4b07-a19d-1a7260fdf3e8




