version: 2.1

jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Start up Services
          command: |
            docker-compose -f docker-compose.test.yml up -d database
            docker-compose -f docker-compose.test.yml up -d redis
            docker-compose -f docker-compose.test.yml up -d zookeeper
            docker-compose -f docker-compose.test.yml up -d kafka
      - run:
          name: Build Up Server
          command: |
            docker-compose -f docker-compose.test.yml build  server
  deploy:
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - run:
          name: Deploy Services to linux ubuntu
          command: |
            echo "Coming Soon"





workflows:
  main:
    jobs:
      - build:
          context: Sonarcloud
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main






